// Dataset 9 SOP "Ringkasan Pengendalian dan SOP Kritikal" resmi PT GECL.
// Sumber: dokumen PDF resmi (diekstrak). Dipakai di form SOP Kritis: pilih SOP -> auto-isi
// metadata (Judul/Risiko/Departemen/Perusahaan/NR0/Tingkat Risiko) + Pengendalian + Langkah.
// Catatan: nama export KARTU_CCC & getKartuCcc dipertahankan agar referensi lama tetap resolve.

export interface KartuCcc {
  id: string;
  judulSop: string;
  risiko: string;
  departemen: string;
  perusahaan: string;
  tanggalPublikasi: string; // YYYY-MM-DD
  nilaiRisikoMurni: string; // "20"
  tingkatRisiko: string; // "Ekstrem" (kotak NR0 merah pada dokumen asli)
  image: string; // path di client/public (dipakai ulang dari aset kartu-ccc)
  /** Daftar Pengendalian Kritikal (Ya/Tidak/N/A). */
  controls: string[];
  /** Daftar Item/Langkah Kritikal (Ya/Tidak). */
  langkah: string[];
}

const PERUSAHAAN = "PT Goden Energi Cemerlang Lestari";

export const KARTU_CCC: KartuCcc[] = [
  {
    id: "dump-truck",
    judulSop: "GECL – HAUL-PPO-4.2.1 – Keselamatan Dump Truck",
    risiko: "Menabrak unit lain mengakibatkan fatality",
    departemen: "Operation",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/dt-tabrakan.jpg",
    controls: [
      "Simper",
      "Fit to work",
      "Pemeriksaan sebelum pengoperasian/P2H",
      "Pemakaian sabuk pengaman",
      "Komunikasi aktif 2 arah",
      "Mengemudi sesuai cuaca dan kondisi jalan",
      "Kepatuhan pada rambu-rambu lalu lintas",
      "Jaga jarak aman",
    ],
    langkah: [
      "Mengikuti P5M tentang pengendalian kritikal (CCC)",
      "Melakukan pemeriksaan kesiapan sebelum bekerja (fit to work)",
      "Melakukan P2H sebelum bekerja (RFU)",
      "Menggunakan safety belt selama mengoperasikan unit",
      "Melakukan komunikasi 2 arah (channel radio yang sesuai, overtaking, pandangan terbatas)",
      "Mengemudi dengan kecepatan yang sesuai dengan rambu di jalan hauling",
      "Melakukan jaga jarak aman beriringan",
    ],
  },
  {
    id: "dumping",
    judulSop: "GECL – HAUL-PPO-4.2.5 – Proses Dumping",
    risiko: "Menabrak unit lain mengakibatkan fatality",
    departemen: "Dumping",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/kendaraan-dekat-orang.jpg",
    controls: [
      "Simper",
      "Fit to work",
      "Pemeriksaan sebelum pengoperasian/P2H",
      "Pemakaian sabuk pengaman",
      "Komunikasi aktif 2 arah",
      "Mengemudi sesuai cuaca dan kondisi jalan",
      "Kepatuhan pada rambu-rambu lalu lintas",
      "Jaga jarak aman",
    ],
    langkah: [
      "Mengikuti P5M tentang pengendalian kritikal (CCC)",
      "Melakukan pemeriksaan kesiapan sebelum bekerja (fit to work)",
      "Melakukan P2H sebelum bekerja (RFU)",
      "Menggunakan safety belt selama mengoperasikan unit",
      "Menggunakan APD yang sesuai",
      "Melakukan komunikasi 2 arah ke operator A2B/spotter (area dumping)",
      "Mengemudi dengan kecepatan di area stockpile 20 km/jam",
      "Melakukan jaga jarak aman saat antri dan dumping di stockpile",
      "Memastikan bak DT turun dengan sempurna pada posisinya (hindari DT rebah)",
      "Dilarang membuka kunci bak manual di area reclaimer/hopper crusher plant",
    ],
  },
  {
    id: "fatigue",
    judulSop: "GECL – HSE-PPO-4.1.16 – Manajemen Fatigue",
    risiko: "Menabrak unit lain mengakibatkan fatality",
    departemen: "HSE",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/kendaraan-menabrak-orang.jpg",
    controls: [
      "Simper",
      "Fit to work",
      "Pemeriksaan sebelum pengoperasian/P2H",
      "Pemakaian sabuk pengaman",
      "Komunikasi aktif 2 arah",
      "Mengemudi sesuai cuaca dan kondisi jalan",
      "Kepatuhan pada rambu-rambu lalu lintas",
      "Jaga jarak aman beriringan",
    ],
    langkah: [
      "Mengikuti P5M tentang pengendalian kritikal (CCC)",
      "Melakukan pemeriksaan kesiapan sebelum bekerja (fit to work)",
      "Melakukan P2H sebelum bekerja (RFU)",
      "Menggunakan safety belt selama mengoperasikan unit",
      "Melakukan komunikasi 2 arah (channel radio yang sesuai, overtaking, pandangan terbatas)",
      "Mengemudi dengan kecepatan yang sesuai dengan rambu di jalan hauling",
      "Melakukan jaga jarak aman beriringan",
      "Tidak mengoperasikan unit dalam keadaan fatigue atau ada masalah pribadi yang mengganggu konsentrasi",
      "Bekerja sesuai dengan roster yang telah ditentukan",
    ],
  },
  {
    id: "light-vehicle",
    judulSop: "GECL – HSE-PPO-4.1.45 – Pengoperasian Light Vehicle",
    risiko: "LV terguling/rebah menyebabkan fatality",
    departemen: "HSE",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/dtlv-terguling.jpg",
    controls: [
      "Simper",
      "Fit to work",
      "Pemeriksaan sebelum pengoperasian/P2H",
      "Pemakaian sabuk pengaman",
      "Komunikasi positif",
      "Mengemudi sesuai cuaca dan kondisi jalan",
      "Kepatuhan pada rambu-rambu lalu lintas",
      "Persyaratan pengangkutan barang/orang",
    ],
    langkah: [
      "Mempunyai simper yang sesuai dan berlaku",
      "P2H unit LV dilakukan setiap awal shift",
      "Gunakan safety belt",
      "Patuhi peraturan dan rambu lalu lintas",
      "Jaga jarak aman minimal 4 detik",
      "Lakukan kontak positif jika mendahului unit lain",
      "Perhatikan kondisi jalan dan kendaraan di belakangnya",
    ],
  },
  {
    id: "light-vehicle-tanggul",
    judulSop: "GECL – HSE-PPO-4.1.45 – Pengoperasian Light Vehicle (lanjutan)",
    risiko: "LV menabrak tanggul/unit lain menyebabkan fatality",
    departemen: "HSE",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/dtlv-terguling.jpg",
    controls: [
      "Simper",
      "Komunikasi positif",
      "Kepatuhan pada rambu-rambu lalu lintas",
      "Jaga jarak aman",
      "P2H",
      "Pemakaian safety belt",
      "Fit to work",
      "Mengemudi sesuai kondisi jalan",
      "Wajib menggunakan lajur kiri",
    ],
    langkah: [
      "Mempunyai simper yang sesuai dan berlaku",
      "P2H unit LV dilakukan setiap awal shift",
      "Laporkan temuan minor atau major jika ada untuk pengecekan dan perbaikan",
      "Panaskan mesin 5 sampai 10 menit sebelum unit LV dioperasikan",
      "Gunakan safety belt",
      "Patuhi peraturan dan rambu lalu lintas",
      "Jaga jarak aman minimal 4 detik",
      "Lakukan kontak positif jika mendahului unit lain",
    ],
  },
  {
    id: "pengelolaan-ban",
    judulSop: "GECL – PLANT-PPO-4.3.16 – Pengelolaan Ban",
    risiko: "Terkena ledakan ban menyebabkan fatality",
    departemen: "PLANT",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/penanganan-ban.jpg",
    controls: [
      "Memastikan ID/Simper sesuai",
      "Inspeksi ban",
      "Maksimum tekanan ban",
      "Jarak/zona aman pemompaan ban",
      "Posisi pekerja yang aman",
      "Hose angin panjang",
      "Kerangkeng pengaman ban",
      "Peralatan pemompa ban standar",
      "Waktu tunggu 15 menit setelah pemompaan",
    ],
    langkah: [
      "Melakukan P5M membahas risiko fatal beserta kontrol kritisnya",
      "Memeriksa peralatan yang akan digunakan layak",
      "Melakukan inspeksi kondisi ban yang akan dipakai kembali",
      "Memasukkan ban ke dalam sangkar pengaman",
      "Memakai hose pengisian yang lebih panjang",
      "Memposisikan pekerja di luar exclusion zone minimal 1,5 meter",
      "Memeriksa tekanan ban secara kontinyu",
      "Menunggu 15 menit setelah ban selesai dipompa",
    ],
  },
  {
    id: "perbengkelan",
    judulSop: "GECL – PLANT-PPO-4.3.17 – Keselamatan Perbengkelan",
    risiko: "Terjepit peralatan menyebabkan fatality",
    departemen: "PLANT",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-04-17",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/perbaikan-dt-hauling.jpg",
    controls: [
      "Fit to work",
      "Prosedur LOTO",
      "Pengaman mekanis (jack stand, ganjal, pengaman dump)",
      "Pengamanan area kerja",
      "Posisi pekerja yang aman",
    ],
    langkah: [
      "Melakukan P5M membahas risiko fatal beserta kontrol kritisnya",
      "Memastikan area kerja aman",
      "Memastikan LOTO sudah terpasang pada unit",
      "Memeriksa peralatan yang akan digunakan layak",
      "Memastikan posisi kerja tidak berada pada titik jepit",
      "Memastikan pemasangan jack stand, ganjal, pengaman dump pada posisi yang benar",
      "Memastikan bekerja lebih dari satu orang",
    ],
  },
  {
    id: "kelistrikan",
    judulSop: "GECL – PLANT-PPO-4.3.7 – Keselamatan Kelistrikan",
    risiko: "Tersetrum listrik mengakibatkan fatality",
    departemen: "Plant",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2017-05-16",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/energi-lepas-servis.jpg",
    controls: [
      "Lisensi/otoritas/kompetensi",
      "Batas jarak aman",
      "Peralatan kerja non konduktif",
      "Peralatan pengetesan kelistrikan",
      "Peralatan pengaman (GFI/grounding)",
      "APD kelistrikan",
    ],
    langkah: [
      "Memiliki kompetensi terkait kelistrikan",
      "Jarak aman 1 meter",
      "Semua peralatan tangan berisolasi SNI/IEC 60900",
      "Multimeter, clamp meter, voltage detector",
      "Ground Fault Interruptor",
      "APD: sarung tangan isolasi, sepatu safety dielektrik, helm insulasi, kacamata arc flash, flame resistant clothing",
    ],
  },
  {
    id: "charging-ev",
    judulSop: "GECL-HAUL-PPO_4.2.11 – Charging Electric Vehicle",
    risiko: "Unit/Charging Station terbakar",
    departemen: "Operation",
    perusahaan: PERUSAHAAN,
    tanggalPublikasi: "2025-11-26",
    nilaiRisikoMurni: "20",
    tingkatRisiko: "Ekstrem",
    image: "/kartu-ccc/charging-station-terbakar.jpg",
    controls: [
      "P2H",
      "Inspeksi area dan peralatan kerja",
      "Memahami prosedur kerja",
      "Penggunaan APD yang sesuai",
      "Kontrol arus listrik",
    ],
    langkah: [
      "Melakukan P2H sebelum charging (kondisi charger, kabel, konektor, grounding, area sekitar)",
      "Memastikan area charging aman, bersih, dan bebas material mudah terbakar",
      "Menggunakan APD sesuai standar (sarung tangan isolasi, sepatu safety, helm)",
      "Memastikan unit EV dalam kondisi mati dan rem parkir aktif sebelum charger",
      "Menghubungkan konektor charger dengan benar dan terkunci sempurna",
      "Menghentikan charging jika terdeteksi panas berlebih, bau terbakar, suara abnormal, atau alarm sistem",
      "Melepas konektor charger setelah proses charging selesai dan sistem dimatikan",
      "Menyimpan kembali kabel dan peralatan charging pada tempat yang disediakan",
    ],
  },
];

export function getKartuCcc(id: string | null | undefined): KartuCcc | undefined {
  if (!id) return undefined;
  return KARTU_CCC.find((k) => k.id === id);
}
