// DIHASILKAN OTOMATIS oleh scripts/gen-rekap-columns.ts — jangan disunting tangan.
// Sumber: "Database & Mapping profil Kesehatan Karyawan PT GECL.xlsx"
//
// Daftar kolom ketiga sheet Rekap dibekukan di sini supaya urutan kolom, keanggotaan
// grup, dan kunci `nilai` tidak berubah-ubah mengikuti isi file yang diunggah.
// Kolom identitas dan kolom ekor berslot khusus (KESIMPULAN, REKOMENDASI, BULAN, TAHUN)
// sengaja DIKECUALIKAN — semuanya punya kolom sendiri di tabel mcu_health_mapping.

export type RekapKategori = "Rekap Fisik" | "Rekap Riwayat" | "Rekap Lab & Non Lab";

export interface KolomRekap {
    /** kunci di dalam mcu_health_mapping.nilai, mis. "TANDA VITAL — Nadi" */
    key: string;
    /** nama grup untuk header dua tingkat */
    grup: string;
    /** teks yang ditampilkan di header bawah */
    label: string;
    /** indeks kolom asli di sheet — untuk pencocokan posisi & audit */
    idx: number;
}

export interface DefinisiRekap {
    kategori: RekapKategori;
    sheet: string;
    barisGrup: number;
    barisHeader: number;
    kolom: KolomRekap[];
}

export const REKAP_KATEGORI: RekapKategori[] = ["Rekap Fisik", "Rekap Riwayat", "Rekap Lab & Non Lab"];

export const REKAP_DEFS: Record<RekapKategori, DefinisiRekap> = {
    "Rekap Fisik": {
        kategori: "Rekap Fisik",
        sheet: "Rekap Fisik",
        barisGrup: 2,
        barisHeader: 3,
        kolom: [
            { key: "TANDA VITAL — Nadi", grup: "TANDA VITAL", label: "Nadi", idx: 12 },
            { key: "TANDA VITAL — Isi", grup: "TANDA VITAL", label: "Isi", idx: 13 },
            { key: "TANDA VITAL — Irama", grup: "TANDA VITAL", label: "Irama", idx: 14 },
            { key: "TANDA VITAL — Pernafasan", grup: "TANDA VITAL", label: "Pernafasan", idx: 15 },
            { key: "TANDA VITAL — Irama (2)", grup: "TANDA VITAL", label: "Irama (Pernafasan)", idx: 16 },
            { key: "TANDA VITAL — Tekanan darah Sistolik (duduk)", grup: "TANDA VITAL", label: "Tekanan darah Sistolik (duduk)", idx: 17 },
            { key: "TANDA VITAL — Tekanan darah Diastolik (duduk)", grup: "TANDA VITAL", label: "Tekanan darah Diastolik (duduk)", idx: 18 },
            { key: "TANDA VITAL — Suhu tubuh", grup: "TANDA VITAL", label: "Suhu tubuh", idx: 19 },
            { key: "STATUS GIZI — Tinggi badan", grup: "STATUS GIZI", label: "Tinggi badan", idx: 20 },
            { key: "STATUS GIZI — Berat badan", grup: "STATUS GIZI", label: "Berat badan", idx: 21 },
            { key: "STATUS GIZI — IMT", grup: "STATUS GIZI", label: "IMT", idx: 22 },
            { key: "STATUS GIZI — Lingkar pinggang", grup: "STATUS GIZI", label: "Lingkar pinggang", idx: 23 },
            { key: "STATUS GIZI — Bentuk badan", grup: "STATUS GIZI", label: "Bentuk badan", idx: 24 },
            { key: "STATUS GIZI — Lain-lain", grup: "STATUS GIZI", label: "Lain-lain", idx: 25 },
            { key: "TINGKAT KESADARAN — Compos mentis", grup: "TINGKAT KESADARAN", label: "Compos mentis", idx: 26 },
            { key: "TINGKAT KESADARAN — Kualitas kontak", grup: "TINGKAT KESADARAN", label: "Kualitas kontak", idx: 27 },
            { key: "KULIT DAN KUKU — Kulit", grup: "KULIT DAN KUKU", label: "Kulit", idx: 28 },
            { key: "KULIT DAN KUKU — Selaput lendir", grup: "KULIT DAN KUKU", label: "Selaput lendir", idx: 29 },
            { key: "KULIT DAN KUKU — Kuku", grup: "KULIT DAN KUKU", label: "Kuku", idx: 30 },
            { key: "KULIT DAN KUKU — Lain2", grup: "KULIT DAN KUKU", label: "Lain2", idx: 31 },
            { key: "KEPALA — Tulang", grup: "KEPALA", label: "Tulang", idx: 32 },
            { key: "KEPALA — Kulit kepala", grup: "KEPALA", label: "Kulit kepala", idx: 33 },
            { key: "KEPALA — Rambut", grup: "KEPALA", label: "Rambut", idx: 34 },
            { key: "KEPALA — Bentuk wajah", grup: "KEPALA", label: "Bentuk wajah", idx: 35 },
            { key: "KEPALA — Lainnya", grup: "KEPALA", label: "Lainnya", idx: 36 },
            { key: "MATA — Persepsi warna", grup: "MATA", label: "Persepsi warna", idx: 37 },
            { key: "MATA — Kelopak mata kanan", grup: "MATA", label: "Kelopak mata kanan", idx: 38 },
            { key: "MATA — Kelopak mata kiri", grup: "MATA", label: "Kelopak mata kiri", idx: 39 },
            { key: "MATA — Konjungtiva kanan", grup: "MATA", label: "Konjungtiva kanan", idx: 40 },
            { key: "MATA — Konjungtiva kiri", grup: "MATA", label: "Konjungtiva kiri", idx: 41 },
            { key: "MATA — Kesegarisan/gerak bola mata kanan", grup: "MATA", label: "Kesegarisan/gerak bola mata kanan", idx: 42 },
            { key: "MATA — Kesegarisan/gerak bola mata kiri", grup: "MATA", label: "Kesegarisan/gerak bola mata kiri", idx: 43 },
            { key: "MATA — Sklera kanan", grup: "MATA", label: "Sklera kanan", idx: 44 },
            { key: "MATA — Sklera kiri", grup: "MATA", label: "Sklera kiri", idx: 45 },
            { key: "MATA — Lensa mata kanan", grup: "MATA", label: "Lensa mata kanan", idx: 46 },
            { key: "MATA — Lensa mata kiri", grup: "MATA", label: "Lensa mata kiri", idx: 47 },
            { key: "Tanpa Kacamata — Visus jauh OD", grup: "Tanpa Kacamata", label: "Visus jauh OD", idx: 48 },
            { key: "Tanpa Kacamata — Visus jauh OS", grup: "Tanpa Kacamata", label: "Visus jauh OS", idx: 49 },
            { key: "Tanpa Kacamata — Visus dekat OD", grup: "Tanpa Kacamata", label: "Visus dekat OD", idx: 50 },
            { key: "Tanpa Kacamata — Visus dekat OS", grup: "Tanpa Kacamata", label: "Visus dekat OS", idx: 51 },
            { key: "Dengan Kacamata — Visus jauh OD", grup: "Dengan Kacamata", label: "Visus jauh OD", idx: 52 },
            { key: "Dengan Kacamata — Visus jauh OS", grup: "Dengan Kacamata", label: "Visus jauh OS", idx: 53 },
            { key: "Dengan Kacamata — Visus dekat OD", grup: "Dengan Kacamata", label: "Visus dekat OD", idx: 54 },
            { key: "Dengan Kacamata — Visus dekat OS", grup: "Dengan Kacamata", label: "Visus dekat OS", idx: 55 },
            { key: "Dengan Kacamata — Lainnya", grup: "Dengan Kacamata", label: "Lainnya", idx: 56 },
            { key: "Telinga — Daun telinga kanan", grup: "Telinga", label: "Daun telinga kanan", idx: 57 },
            { key: "Telinga — Daun telinga kiri", grup: "Telinga", label: "Daun telinga kiri", idx: 58 },
            { key: "Telinga — Liang telinga kanan", grup: "Telinga", label: "Liang telinga kanan", idx: 59 },
            { key: "Telinga — Liang telinga kiri", grup: "Telinga", label: "Liang telinga kiri", idx: 60 },
            { key: "Telinga — Serumen kanan", grup: "Telinga", label: "Serumen kanan", idx: 61 },
            { key: "Telinga — Serumen kiri", grup: "Telinga", label: "Serumen kiri", idx: 62 },
            { key: "Telinga — Membrana timpani kanan", grup: "Telinga", label: "Membrana timpani kanan", idx: 63 },
            { key: "Telinga — Membrana timpani kiri", grup: "Telinga", label: "Membrana timpani kiri", idx: 64 },
            { key: "Telinga — Kesan pendengaran kanan", grup: "Telinga", label: "Kesan pendengaran kanan", idx: 65 },
            { key: "Telinga — Kesan pendengaran kiri", grup: "Telinga", label: "Kesan pendengaran kiri", idx: 66 },
            { key: "Telinga — Lain2", grup: "Telinga", label: "Lain2", idx: 67 },
            { key: "HIDUNG — Meatus nasi", grup: "HIDUNG", label: "Meatus nasi", idx: 68 },
            { key: "HIDUNG — Septum nasi", grup: "HIDUNG", label: "Septum nasi", idx: 69 },
            { key: "HIDUNG — Konka nasal", grup: "HIDUNG", label: "Konka nasal", idx: 70 },
            { key: "HIDUNG — Nyeri ketok sinus maksilaris", grup: "HIDUNG", label: "Nyeri ketok sinus maksilaris", idx: 71 },
            { key: "HIDUNG — Lain2", grup: "HIDUNG", label: "Lain2", idx: 72 },
            { key: "TENGGOROKAN — Pharynx", grup: "TENGGOROKAN", label: "Pharynx", idx: 73 },
            { key: "TENGGOROKAN — Tonsil Kanan", grup: "TENGGOROKAN", label: "Tonsil Kanan", idx: 74 },
            { key: "TENGGOROKAN — Ukuran", grup: "TENGGOROKAN", label: "Ukuran", idx: 75 },
            { key: "TENGGOROKAN — Tonsil Kiri", grup: "TENGGOROKAN", label: "Tonsil Kiri", idx: 76 },
            { key: "TENGGOROKAN — Ukuran (2)", grup: "TENGGOROKAN", label: "Ukuran (Tonsil Kiri)", idx: 77 },
            { key: "TENGGOROKAN — Palatum", grup: "TENGGOROKAN", label: "Palatum", idx: 78 },
            { key: "TENGGOROKAN — Lain2", grup: "TENGGOROKAN", label: "Lain2", idx: 79 },
            { key: "MULUT — Bibir", grup: "MULUT", label: "Bibir", idx: 80 },
            { key: "MULUT — Lidah", grup: "MULUT", label: "Lidah", idx: 81 },
            { key: "MULUT — Gusi", grup: "MULUT", label: "Gusi", idx: 82 },
            { key: "MULUT — Lain2", grup: "MULUT", label: "Lain2", idx: 83 },
            { key: "LEHER — Gerakan leher", grup: "LEHER", label: "Gerakan leher", idx: 84 },
            { key: "LEHER — Kelenjar thyroid", grup: "LEHER", label: "Kelenjar thyroid", idx: 85 },
            { key: "LEHER — Pulsasi carotis", grup: "LEHER", label: "Pulsasi carotis", idx: 86 },
            { key: "LEHER — Tekanan vena jugularis", grup: "LEHER", label: "Tekanan vena jugularis", idx: 87 },
            { key: "LEHER — Trachea", grup: "LEHER", label: "Trachea", idx: 88 },
            { key: "LEHER — Lain2", grup: "LEHER", label: "Lain2", idx: 89 },
            { key: "DADA — Bentuk", grup: "DADA", label: "Bentuk", idx: 90 },
            { key: "DADA — Mammae", grup: "DADA", label: "Mammae", idx: 91 },
            { key: "DADA — Tumor", grup: "DADA", label: "Tumor", idx: 92 },
            { key: "DADA — Lain2", grup: "DADA", label: "Lain2", idx: 93 },
            { key: "PARU -PARU & JANTUNG — Palpasi", grup: "PARU -PARU & JANTUNG", label: "Palpasi", idx: 94 },
            { key: "PARU -PARU & JANTUNG — Perkusi kanan", grup: "PARU -PARU & JANTUNG", label: "Perkusi kanan", idx: 95 },
            { key: "PARU -PARU & JANTUNG — Perkusi kiri", grup: "PARU -PARU & JANTUNG", label: "Perkusi kiri", idx: 96 },
            { key: "PARU -PARU & JANTUNG — Iktus kordis", grup: "PARU -PARU & JANTUNG", label: "Iktus kordis", idx: 97 },
            { key: "PARU -PARU & JANTUNG — Batas jantung", grup: "PARU -PARU & JANTUNG", label: "Batas jantung", idx: 98 },
            { key: "PARU -PARU & JANTUNG — Bunyi napas", grup: "PARU -PARU & JANTUNG", label: "Bunyi napas", idx: 99 },
            { key: "PARU -PARU & JANTUNG — Bunyi napas tambahan", grup: "PARU -PARU & JANTUNG", label: "Bunyi napas tambahan", idx: 100 },
            { key: "PARU -PARU & JANTUNG — Bunyi jantung", grup: "PARU -PARU & JANTUNG", label: "Bunyi jantung", idx: 101 },
            { key: "ABDOMEN — Inspeksi", grup: "ABDOMEN", label: "Inspeksi", idx: 102 },
            { key: "ABDOMEN — Perkusi", grup: "ABDOMEN", label: "Perkusi", idx: 103 },
            { key: "ABDOMEN — Auskultasi bising usus", grup: "ABDOMEN", label: "Auskultasi bising usus", idx: 104 },
            { key: "ABDOMEN — Hati", grup: "ABDOMEN", label: "Hati", idx: 105 },
            { key: "ABDOMEN — Limpa", grup: "ABDOMEN", label: "Limpa", idx: 106 },
            { key: "ABDOMEN — Nyeri ketok kanan", grup: "ABDOMEN", label: "Nyeri ketok kanan", idx: 107 },
            { key: "ABDOMEN — Nyeri ketok kiri", grup: "ABDOMEN", label: "Nyeri ketok kiri", idx: 108 },
            { key: "ABDOMEN — Ballotement kanan", grup: "ABDOMEN", label: "Ballotement kanan", idx: 109 },
            { key: "ABDOMEN — Ballotement kiri", grup: "ABDOMEN", label: "Ballotement kiri", idx: 110 },
            { key: "ABDOMEN — Kandung kemih", grup: "ABDOMEN", label: "Kandung kemih", idx: 111 },
            { key: "ABDOMEN — Anus/rektum/perianal", grup: "ABDOMEN", label: "Anus/rektum/perianal", idx: 112 },
            { key: "ABDOMEN — Genitalia eks", grup: "ABDOMEN", label: "Genitalia eks", idx: 113 },
            { key: "ABDOMEN — Prostat", grup: "ABDOMEN", label: "Prostat", idx: 114 },
            { key: "ABDOMEN — Lain-lain", grup: "ABDOMEN", label: "Lain-lain", idx: 115 },
            { key: "EXTREMITAS ATAS — Vertebra", grup: "EXTREMITAS ATAS", label: "Vertebra", idx: 116 },
            { key: "EXTREMITAS ATAS — Nyeri tekan", grup: "EXTREMITAS ATAS", label: "Nyeri tekan", idx: 117 },
            { key: "EXTREMITAS ATAS — Spasme", grup: "EXTREMITAS ATAS", label: "Spasme", idx: 118 },
            { key: "EXTREMITAS ATAS — Bentuk dan simetrisitas", grup: "EXTREMITAS ATAS", label: "Bentuk dan simetrisitas", idx: 119 },
            { key: "EXTREMITAS ATAS — Gerakan kanan", grup: "EXTREMITAS ATAS", label: "Gerakan kanan", idx: 120 },
            { key: "EXTREMITAS ATAS — Gerakan kiri", grup: "EXTREMITAS ATAS", label: "Gerakan kiri", idx: 121 },
            { key: "EXTREMITAS ATAS — Kekuatan kanan", grup: "EXTREMITAS ATAS", label: "Kekuatan kanan", idx: 122 },
            { key: "EXTREMITAS ATAS — Kekuatan kiri", grup: "EXTREMITAS ATAS", label: "Kekuatan kiri", idx: 123 },
            { key: "EXTREMITAS ATAS — Tulang dan sendi kanan", grup: "EXTREMITAS ATAS", label: "Tulang dan sendi kanan", idx: 124 },
            { key: "EXTREMITAS ATAS — Tulang dan sendi kiri", grup: "EXTREMITAS ATAS", label: "Tulang dan sendi kiri", idx: 125 },
            { key: "EXTREMITAS ATAS — Sensibilitas kanan", grup: "EXTREMITAS ATAS", label: "Sensibilitas kanan", idx: 126 },
            { key: "EXTREMITAS ATAS — Sensibilitas kiri", grup: "EXTREMITAS ATAS", label: "Sensibilitas kiri", idx: 127 },
            { key: "EXTREMITAS ATAS — Vaskular kanan", grup: "EXTREMITAS ATAS", label: "Vaskular kanan", idx: 128 },
            { key: "EXTREMITAS ATAS — Vaskular  kiri", grup: "EXTREMITAS ATAS", label: "Vaskular  kiri", idx: 129 },
            { key: "EXTREMITAS BAWAH — Bentuk dan simetrisitas", grup: "EXTREMITAS BAWAH", label: "Bentuk dan simetrisitas", idx: 130 },
            { key: "EXTREMITAS BAWAH — Gerakan kanan", grup: "EXTREMITAS BAWAH", label: "Gerakan kanan", idx: 131 },
            { key: "EXTREMITAS BAWAH — Gerakan kiri", grup: "EXTREMITAS BAWAH", label: "Gerakan kiri", idx: 132 },
            { key: "EXTREMITAS BAWAH — Kekuatan kanan", grup: "EXTREMITAS BAWAH", label: "Kekuatan kanan", idx: 133 },
            { key: "EXTREMITAS BAWAH — Kekuatan kiri", grup: "EXTREMITAS BAWAH", label: "Kekuatan kiri", idx: 134 },
            { key: "EXTREMITAS BAWAH — Tulang dan sendi kanan", grup: "EXTREMITAS BAWAH", label: "Tulang dan sendi kanan", idx: 135 },
            { key: "EXTREMITAS BAWAH — Tulang dan sendi kiri", grup: "EXTREMITAS BAWAH", label: "Tulang dan sendi kiri", idx: 136 },
            { key: "EXTREMITAS BAWAH — Sensibilitas kanan", grup: "EXTREMITAS BAWAH", label: "Sensibilitas kanan", idx: 137 },
            { key: "EXTREMITAS BAWAH — Sensibilitas kiri", grup: "EXTREMITAS BAWAH", label: "Sensibilitas kiri", idx: 138 },
            { key: "EXTREMITAS BAWAH — Vaskular kanan", grup: "EXTREMITAS BAWAH", label: "Vaskular kanan", idx: 139 },
            { key: "EXTREMITAS BAWAH — Vaskular kiri", grup: "EXTREMITAS BAWAH", label: "Vaskular kiri", idx: 140 },
            { key: "EXTREMITAS BAWAH — Lain-lain", grup: "EXTREMITAS BAWAH", label: "Lain-lain", idx: 141 },
            { key: "SARAF/FUNGSI LUHUR — Daya ingat", grup: "SARAF/FUNGSI LUHUR", label: "Daya ingat", idx: 142 },
            { key: "SARAF/FUNGSI LUHUR — Orientasi : waktu", grup: "SARAF/FUNGSI LUHUR", label: "Orientasi : waktu", idx: 143 },
            { key: "SARAF/FUNGSI LUHUR — Orientasi : orang", grup: "SARAF/FUNGSI LUHUR", label: "Orientasi : orang", idx: 144 },
            { key: "SARAF/FUNGSI LUHUR — Orientasi : tempat", grup: "SARAF/FUNGSI LUHUR", label: "Orientasi : tempat", idx: 145 },
            { key: "SARAF/FUNGSI LUHUR — Sikap", grup: "SARAF/FUNGSI LUHUR", label: "Sikap", idx: 146 },
            { key: "SARAF/FUNGSI LUHUR — Kesan saraf otak", grup: "SARAF/FUNGSI LUHUR", label: "Kesan saraf otak", idx: 147 },
            { key: "KESAN SARAF OTAK — Fungsi sensorik kanan", grup: "KESAN SARAF OTAK", label: "Fungsi sensorik kanan", idx: 148 },
            { key: "KESAN SARAF OTAK — Fungsi sensorik kiri", grup: "KESAN SARAF OTAK", label: "Fungsi sensorik kiri", idx: 149 },
            { key: "KESAN SARAF OTAK — Fungsi otonom kanan", grup: "KESAN SARAF OTAK", label: "Fungsi otonom kanan", idx: 150 },
            { key: "KESAN SARAF OTAK — Fungsi otonom kiri", grup: "KESAN SARAF OTAK", label: "Fungsi otonom kiri", idx: 151 },
            { key: "KESAN SARAF OTAK — Gerakan abnormal kanan", grup: "KESAN SARAF OTAK", label: "Gerakan abnormal kanan", idx: 152 },
            { key: "KESAN SARAF OTAK — Gerakan abnormal kiri", grup: "KESAN SARAF OTAK", label: "Gerakan abnormal kiri", idx: 153 },
            { key: "KESAN SARAF OTAK — Refleksi fisiologis patela kanan", grup: "KESAN SARAF OTAK", label: "Refleksi fisiologis patela kanan", idx: 154 },
            { key: "KESAN SARAF OTAK — Refleksi fisiologis patela kiri", grup: "KESAN SARAF OTAK", label: "Refleksi fisiologis patela kiri", idx: 155 },
            { key: "KESAN SARAF OTAK — Refleksi biseps dan troceps kanan", grup: "KESAN SARAF OTAK", label: "Refleksi biseps dan troceps kanan", idx: 156 },
            { key: "KESAN SARAF OTAK — Refleksi biseps dan troceps kiri", grup: "KESAN SARAF OTAK", label: "Refleksi biseps dan troceps kiri", idx: 157 },
            { key: "KESAN SARAF OTAK — Refleksi patologis babinsky kanan", grup: "KESAN SARAF OTAK", label: "Refleksi patologis babinsky kanan", idx: 158 },
            { key: "KESAN SARAF OTAK — Refleksi patologis babinsky kiri", grup: "KESAN SARAF OTAK", label: "Refleksi patologis babinsky kiri", idx: 159 },
            { key: "KESAN SARAF OTAK — Lain-lain", grup: "KESAN SARAF OTAK", label: "Lain-lain", idx: 160 },
            { key: "KELENJAR GETAH BENING — Leher", grup: "KELENJAR GETAH BENING", label: "Leher", idx: 161 },
            { key: "KELENJAR GETAH BENING — Submandibula", grup: "KELENJAR GETAH BENING", label: "Submandibula", idx: 162 },
            { key: "KELENJAR GETAH BENING — Ketiak", grup: "KELENJAR GETAH BENING", label: "Ketiak", idx: 163 },
            { key: "KELENJAR GETAH BENING — Inguinal", grup: "KELENJAR GETAH BENING", label: "Inguinal", idx: 164 },
            { key: "Kesimpulan Gigi", grup: "Lainnya", label: "Kesimpulan Gigi", idx: 165 },
            { key: "STATUS KESEHATAN", grup: "Lainnya", label: "STATUS KESEHATAN", idx: 168 },
            { key: "TANGGAL", grup: "Lainnya", label: "TANGGAL", idx: 169 },
        ],
    },
    "Rekap Riwayat": {
        kategori: "Rekap Riwayat",
        sheet: "Rekap Riwayat",
        barisGrup: 1,
        barisHeader: 2,
        kolom: [
            { key: "RIWAYAT KESEHATAN — Diphteria", grup: "RIWAYAT KESEHATAN", label: "Diphteria", idx: 11 },
            { key: "RIWAYAT KESEHATAN — Sinusitis", grup: "RIWAYAT KESEHATAN", label: "Sinusitis", idx: 12 },
            { key: "RIWAYAT KESEHATAN — Bronchitis", grup: "RIWAYAT KESEHATAN", label: "Bronchitis", idx: 13 },
            { key: "RIWAYAT KESEHATAN — Batuk Darah", grup: "RIWAYAT KESEHATAN", label: "Batuk Darah", idx: 14 },
            { key: "RIWAYAT KESEHATAN — TBC", grup: "RIWAYAT KESEHATAN", label: "TBC", idx: 15 },
            { key: "RIWAYAT KESEHATAN — Radang Paru", grup: "RIWAYAT KESEHATAN", label: "Radang Paru", idx: 16 },
            { key: "RIWAYAT KESEHATAN — Asthma", grup: "RIWAYAT KESEHATAN", label: "Asthma", idx: 17 },
            { key: "RIWAYAT KESEHATAN — Sesak Nafas", grup: "RIWAYAT KESEHATAN", label: "Sesak Nafas", idx: 18 },
            { key: "RIWAYAT KESEHATAN — Sulit buang air kecil", grup: "RIWAYAT KESEHATAN", label: "Sulit buang air kecil", idx: 19 },
            { key: "RIWAYAT KESEHATAN — Saluran kemih", grup: "RIWAYAT KESEHATAN", label: "Saluran kemih", idx: 20 },
            { key: "RIWAYAT KESEHATAN — Penyakit ginjal", grup: "RIWAYAT KESEHATAN", label: "Penyakit ginjal", idx: 21 },
            { key: "RIWAYAT KESEHATAN — Kencing batu", grup: "RIWAYAT KESEHATAN", label: "Kencing batu", idx: 22 },
            { key: "RIWAYAT KESEHATAN — Inskontinensia urin", grup: "RIWAYAT KESEHATAN", label: "Inskontinensia urin", idx: 23 },
            { key: "RIWAYAT KESEHATAN — Radang selaput otak", grup: "RIWAYAT KESEHATAN", label: "Radang selaput otak", idx: 24 },
            { key: "RIWAYAT KESEHATAN — Gegar otak", grup: "RIWAYAT KESEHATAN", label: "Gegar otak", idx: 25 },
            { key: "RIWAYAT KESEHATAN — Polio", grup: "RIWAYAT KESEHATAN", label: "Polio", idx: 26 },
            { key: "RIWAYAT KESEHATAN — Ayan / Epilepsi", grup: "RIWAYAT KESEHATAN", label: "Ayan / Epilepsi", idx: 27 },
            { key: "RIWAYAT KESEHATAN — Stroke / Lumpuh", grup: "RIWAYAT KESEHATAN", label: "Stroke / Lumpuh", idx: 28 },
            { key: "RIWAYAT KESEHATAN — Sakit kepala", grup: "RIWAYAT KESEHATAN", label: "Sakit kepala", idx: 29 },
            { key: "RIWAYAT KESEHATAN — Typus", grup: "RIWAYAT KESEHATAN", label: "Typus", idx: 30 },
            { key: "RIWAYAT KESEHATAN — Muntah darah", grup: "RIWAYAT KESEHATAN", label: "Muntah darah", idx: 31 },
            { key: "RIWAYAT KESEHATAN — Sulit buang air besar", grup: "RIWAYAT KESEHATAN", label: "Sulit buang air besar", idx: 32 },
            { key: "RIWAYAT KESEHATAN — Sakit lambung / maag", grup: "RIWAYAT KESEHATAN", label: "Sakit lambung / maag", idx: 33 },
            { key: "RIWAYAT KESEHATAN — Penyakit kuning", grup: "RIWAYAT KESEHATAN", label: "Penyakit kuning", idx: 34 },
            { key: "RIWAYAT KESEHATAN — Penyakit kandung empedu", grup: "RIWAYAT KESEHATAN", label: "Penyakit kandung empedu", idx: 35 },
            { key: "RIWAYAT KESEHATAN — Gangguan menelan", grup: "RIWAYAT KESEHATAN", label: "Gangguan menelan", idx: 36 },
            { key: "RIWAYAT KESEHATAN — Inskontinensia alvi", grup: "RIWAYAT KESEHATAN", label: "Inskontinensia alvi", idx: 37 },
            { key: "RIWAYAT KESEHATAN — Cacar air", grup: "RIWAYAT KESEHATAN", label: "Cacar air", idx: 38 },
            { key: "RIWAYAT KESEHATAN — Jamur kulit", grup: "RIWAYAT KESEHATAN", label: "Jamur kulit", idx: 39 },
            { key: "RIWAYAT KESEHATAN — Penyakit kelamin", grup: "RIWAYAT KESEHATAN", label: "Penyakit kelamin", idx: 40 },
            { key: "RIWAYAT KESEHATAN — Serangan jantung", grup: "RIWAYAT KESEHATAN", label: "Serangan jantung", idx: 41 },
            { key: "RIWAYAT KESEHATAN — Nyeri dada", grup: "RIWAYAT KESEHATAN", label: "Nyeri dada", idx: 42 },
            { key: "RIWAYAT KESEHATAN — Rasa berdebar", grup: "RIWAYAT KESEHATAN", label: "Rasa berdebar", idx: 43 },
            { key: "RIWAYAT KESEHATAN — Tekanan darah tinggi", grup: "RIWAYAT KESEHATAN", label: "Tekanan darah tinggi", idx: 44 },
            { key: "RIWAYAT KESEHATAN — Ambeien / wasir", grup: "RIWAYAT KESEHATAN", label: "Ambeien / wasir", idx: 45 },
            { key: "RIWAYAT KESEHATAN — Varises", grup: "RIWAYAT KESEHATAN", label: "Varises", idx: 46 },
            { key: "RIWAYAT KESEHATAN — Penyakit gondok / thyroid", grup: "RIWAYAT KESEHATAN", label: "Penyakit gondok / thyroid", idx: 47 },
            { key: "RIWAYAT KESEHATAN — Radang sendi / rematik", grup: "RIWAYAT KESEHATAN", label: "Radang sendi / rematik", idx: 48 },
            { key: "RIWAYAT KESEHATAN — Alergi makanan", grup: "RIWAYAT KESEHATAN", label: "Alergi makanan", idx: 49 },
            { key: "RIWAYAT KESEHATAN — Alergi Obat", grup: "RIWAYAT KESEHATAN", label: "Alergi Obat", idx: 50 },
            { key: "RIWAYAT KESEHATAN — Tetanus", grup: "RIWAYAT KESEHATAN", label: "Tetanus", idx: 51 },
            { key: "RIWAYAT KESEHATAN — Pingsan", grup: "RIWAYAT KESEHATAN", label: "Pingsan", idx: 52 },
            { key: "RIWAYAT KESEHATAN — Pelupa", grup: "RIWAYAT KESEHATAN", label: "Pelupa", idx: 53 },
            { key: "RIWAYAT KESEHATAN — Sulit konsentrasi", grup: "RIWAYAT KESEHATAN", label: "Sulit konsentrasi", idx: 54 },
            { key: "RIWAYAT KESEHATAN — Gangguan penglihatan", grup: "RIWAYAT KESEHATAN", label: "Gangguan penglihatan", idx: 55 },
            { key: "RIWAYAT KESEHATAN — Gangguan pendengaran", grup: "RIWAYAT KESEHATAN", label: "Gangguan pendengaran", idx: 56 },
            { key: "RIWAYAT KESEHATAN — Sakit pinggang", grup: "RIWAYAT KESEHATAN", label: "Sakit pinggang", idx: 57 },
            { key: "RIWAYAT KESEHATAN — Tumor ganas / kanker", grup: "RIWAYAT KESEHATAN", label: "Tumor ganas / kanker", idx: 58 },
            { key: "RIWAYAT KESEHATAN — Penyakit jiwa", grup: "RIWAYAT KESEHATAN", label: "Penyakit jiwa", idx: 59 },
            { key: "RIWAYAT KESEHATAN — TBC kulit", grup: "RIWAYAT KESEHATAN", label: "TBC kulit", idx: 60 },
            { key: "RIWAYAT KESEHATAN — TBC tulang dan lainnya", grup: "RIWAYAT KESEHATAN", label: "TBC tulang dan lainnya", idx: 61 },
            { key: "RIWAYAT KESEHATAN — Campak", grup: "RIWAYAT KESEHATAN", label: "Campak", idx: 62 },
            { key: "RIWAYAT KESEHATAN — Malaria", grup: "RIWAYAT KESEHATAN", label: "Malaria", idx: 63 },
            { key: "RIWAYAT KESEHATAN — Diabetes", grup: "RIWAYAT KESEHATAN", label: "Diabetes", idx: 64 },
            { key: "RIWAYAT KESEHATAN — Gangguan tidur", grup: "RIWAYAT KESEHATAN", label: "Gangguan tidur", idx: 65 },
            { key: "RIWAYAT KESEHATAN — Pernah dirawat di rumah sakit ?", grup: "RIWAYAT KESEHATAN", label: "Pernah dirawat di rumah sakit ?", idx: 66 },
            { key: "RIWAYAT KESEHATAN — Apakah pernah mengalami kecelakaan", grup: "RIWAYAT KESEHATAN", label: "Apakah pernah mengalami kecelakaan", idx: 67 },
            { key: "RIWAYAT KESEHATAN — Pernah dioperasi ?", grup: "RIWAYAT KESEHATAN", label: "Pernah dioperasi ?", idx: 68 },
            { key: "RIWAYAT KESEHATAN — Hepatitis A", grup: "RIWAYAT KESEHATAN", label: "Hepatitis A", idx: 69 },
            { key: "RIWAYAT KESEHATAN — Hepatitis B", grup: "RIWAYAT KESEHATAN", label: "Hepatitis B", idx: 70 },
            { key: "RIWAYAT KESEHATAN — Typhoid", grup: "RIWAYAT KESEHATAN", label: "Typhoid", idx: 71 },
            { key: "RIWAYAT KESEHATAN — BCG", grup: "RIWAYAT KESEHATAN", label: "BCG", idx: 72 },
            { key: "RIWAYAT KESEHATAN — Polio (2)", grup: "RIWAYAT KESEHATAN", label: "Polio (Imunisasi)", idx: 73 },
            { key: "RIWAYAT KESEHATAN — DPT", grup: "RIWAYAT KESEHATAN", label: "DPT", idx: 74 },
            { key: "RIWAYAT KESEHATAN — BULAN", grup: "RIWAYAT KESEHATAN", label: "BULAN", idx: 75 },
            { key: "RIWAYAT KESEHATAN — Tetanus (2)", grup: "RIWAYAT KESEHATAN", label: "Tetanus (Imunisasi)", idx: 76 },
            { key: "RIWAYAT KESEHATAN — Lain-lain", grup: "RIWAYAT KESEHATAN", label: "Lain-lain", idx: 77 },
            { key: "RIWAYAT KESEHATAN — KELUHAN SAAT INI", grup: "RIWAYAT KESEHATAN", label: "KELUHAN SAAT INI", idx: 78 },
            { key: "RIWAYAT KESEHATAN — Minuman alkohol", grup: "RIWAYAT KESEHATAN", label: "Minuman alkohol", idx: 79 },
            { key: "RIWAYAT KESEHATAN — Merokok", grup: "RIWAYAT KESEHATAN", label: "Merokok", idx: 80 },
            { key: "RIWAYAT KESEHATAN — Mulai merokok pada usia", grup: "RIWAYAT KESEHATAN", label: "Mulai merokok pada usia", idx: 81 },
            { key: "RIWAYAT KESEHATAN — Mulai berhenti merokok tahun", grup: "RIWAYAT KESEHATAN", label: "Mulai berhenti merokok tahun", idx: 82 },
            { key: "RIWAYAT KESEHATAN — Olahraga", grup: "RIWAYAT KESEHATAN", label: "Olahraga", idx: 83 },
            { key: "RIWAYAT KESEHATAN — OBAT-OBATAN YANG SERING DIGUNAKAN", grup: "RIWAYAT KESEHATAN", label: "OBAT-OBATAN YANG SERING DIGUNAKAN", idx: 84 },
            { key: "RIWAYAT KESEHATAN — ALERGI TERHADAP", grup: "RIWAYAT KESEHATAN", label: "ALERGI TERHADAP", idx: 85 },
            { key: "PAJANAN FISIKA — Kebisingan", grup: "PAJANAN FISIKA", label: "Kebisingan", idx: 86 },
            { key: "PAJANAN FISIKA — Suhu panas", grup: "PAJANAN FISIKA", label: "Suhu panas", idx: 87 },
            { key: "PAJANAN FISIKA — Suhu dingin", grup: "PAJANAN FISIKA", label: "Suhu dingin", idx: 88 },
            { key: "PAJANAN FISIKA — Radiasi bukan pengion", grup: "PAJANAN FISIKA", label: "Radiasi bukan pengion", idx: 89 },
            { key: "PAJANAN FISIKA — Radiasi pengion (sinar x, sinar gamma)", grup: "PAJANAN FISIKA", label: "Radiasi pengion (sinar x, sinar gamma)", idx: 90 },
            { key: "PAJANAN FISIKA — Getaran lokal", grup: "PAJANAN FISIKA", label: "Getaran lokal", idx: 91 },
            { key: "PAJANAN FISIKA — Getaran seluruh tubuh", grup: "PAJANAN FISIKA", label: "Getaran seluruh tubuh", idx: 92 },
            { key: "PAJANAN FISIKA — Ketinggian", grup: "PAJANAN FISIKA", label: "Ketinggian", idx: 93 },
            { key: "PAJANAN KIMIA — Debu anorganik (silika, semen, dll)", grup: "PAJANAN KIMIA", label: "Debu anorganik (silika, semen, dll)", idx: 94 },
            { key: "PAJANAN KIMIA — Debu organik - kapas", grup: "PAJANAN KIMIA", label: "Debu organik - kapas", idx: 95 },
            { key: "PAJANAN KIMIA — Asap", grup: "PAJANAN KIMIA", label: "Asap", idx: 96 },
            { key: "PAJANAN KIMIA — Logam berat (Timah hitam, Air raksa dll)", grup: "PAJANAN KIMIA", label: "Logam berat (Timah hitam, Air raksa dll)", idx: 97 },
            { key: "PAJANAN KIMIA — Pelarut organik (benzene, alkil, toluen,", grup: "PAJANAN KIMIA", label: "Pelarut organik (benzene, alkil, toluen,", idx: 98 },
            { key: "PAJANAN KIMIA — Iritan asam (Air keras, Asam sulfat)", grup: "PAJANAN KIMIA", label: "Iritan asam (Air keras, Asam sulfat)", idx: 99 },
            { key: "PAJANAN KIMIA — Iritan basa (Amoniak, Soda api)", grup: "PAJANAN KIMIA", label: "Iritan basa (Amoniak, Soda api)", idx: 100 },
            { key: "PAJANAN KIMIA — Cairan pembersih lain (Amonia, Klor, dll", grup: "PAJANAN KIMIA", label: "Cairan pembersih lain (Amonia, Klor, dll", idx: 101 },
            { key: "PAJANAN KIMIA — Pestisida", grup: "PAJANAN KIMIA", label: "Pestisida", idx: 102 },
            { key: "PAJANAN KIMIA — Uap logam (Mangan, Seng)", grup: "PAJANAN KIMIA", label: "Uap logam (Mangan, Seng)", idx: 103 },
            { key: "PAJANAN BIOLOGI — Bakteri / Virus / jamur / parasit", grup: "PAJANAN BIOLOGI", label: "Bakteri / Virus / jamur / parasit", idx: 104 },
            { key: "PAJANAN BIOLOGI — Darah/cairan tubuh lain", grup: "PAJANAN BIOLOGI", label: "Darah/cairan tubuh lain", idx: 105 },
            { key: "PAJANAN BIOLOGI — Nyamuk/serangga/lain-lain", grup: "PAJANAN BIOLOGI", label: "Nyamuk/serangga/lain-lain", idx: 106 },
            { key: "PAJANAN BIOLOGI — Limbah (kotoran manusia/hewan)", grup: "PAJANAN BIOLOGI", label: "Limbah (kotoran manusia/hewan)", idx: 107 },
            { key: "PAJANAN PSIKOLOGIS — Beban kerja tidak sesuai", grup: "PAJANAN PSIKOLOGIS", label: "Beban kerja tidak sesuai", idx: 108 },
            { key: "PAJANAN PSIKOLOGIS — Pekerjaan tidak sesuai", grup: "PAJANAN PSIKOLOGIS", label: "Pekerjaan tidak sesuai", idx: 109 },
            { key: "PAJANAN PSIKOLOGIS — Ketidakjelasan tugas", grup: "PAJANAN PSIKOLOGIS", label: "Ketidakjelasan tugas", idx: 110 },
            { key: "PAJANAN PSIKOLOGIS — Hambatan jenjang karir", grup: "PAJANAN PSIKOLOGIS", label: "Hambatan jenjang karir", idx: 111 },
            { key: "PAJANAN PSIKOLOGIS — Bekerja giliran (Shift)", grup: "PAJANAN PSIKOLOGIS", label: "Bekerja giliran (Shift)", idx: 112 },
            { key: "PAJANAN PSIKOLOGIS — Konflik dengan teman sekerja", grup: "PAJANAN PSIKOLOGIS", label: "Konflik dengan teman sekerja", idx: 113 },
            { key: "PAJANAN PSIKOLOGIS — Konflik dalam keluarga", grup: "PAJANAN PSIKOLOGIS", label: "Konflik dalam keluarga", idx: 114 },
            { key: "PAJANAN ERGONOMI — Gerakan berulang dengan tangan", grup: "PAJANAN ERGONOMI", label: "Gerakan berulang dengan tangan", idx: 115 },
            { key: "PAJANAN ERGONOMI — Angkat/angkut berat", grup: "PAJANAN ERGONOMI", label: "Angkat/angkut berat", idx: 116 },
            { key: "PAJANAN ERGONOMI — Duduk lama", grup: "PAJANAN ERGONOMI", label: "Duduk lama", idx: 117 },
            { key: "PAJANAN ERGONOMI — Berdiri lama", grup: "PAJANAN ERGONOMI", label: "Berdiri lama", idx: 118 },
            { key: "PAJANAN ERGONOMI — Posisi tubuh tidak anatomis", grup: "PAJANAN ERGONOMI", label: "Posisi tubuh tidak anatomis", idx: 119 },
            { key: "PAJANAN ERGONOMI — Pencahayaan", grup: "PAJANAN ERGONOMI", label: "Pencahayaan", idx: 120 },
            { key: "PAJANAN ERGONOMI — Bekerja dng layar/monitor 4 jam/lebih", grup: "PAJANAN ERGONOMI", label: "Bekerja dng layar/monitor 4 jam/lebih", idx: 121 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Darah tinggi", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Darah tinggi", idx: 122 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Kanker", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Kanker", idx: 123 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Ambeien", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Ambeien", idx: 124 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Asma", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Asma", idx: 125 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Jantung", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Jantung", idx: 126 },
            { key: "RIWAYAT KESEHATAN KELUARGA — TBC", grup: "RIWAYAT KESEHATAN KELUARGA", label: "TBC", idx: 127 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Stroke/Lumpuh separuh badan", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Stroke/Lumpuh separuh badan", idx: 128 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Kencing Manis", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Kencing Manis", idx: 129 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Gangguan jiwa", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Gangguan jiwa", idx: 130 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Penyakit kuning/Hati", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Penyakit kuning/Hati", idx: 131 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Kelainan Darah (Thallasemia dll)", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Kelainan Darah (Thallasemia dll)", idx: 132 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Keadaan Ayah dan Ibu saat ini", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Keadaan Ayah dan Ibu saat ini", idx: 133 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Hari pertama haid terakhir (HPHT)", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Hari pertama haid terakhir (HPHT)", idx: 134 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Lama haid", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Lama haid", idx: 135 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Siklus haid", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Siklus haid", idx: 136 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Nyeri haid", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Nyeri haid", idx: 137 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Banyak haid", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Banyak haid", idx: 138 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Hamil", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Hamil", idx: 139 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Melahirkan", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Melahirkan", idx: 140 },
            { key: "RIWAYAT KESEHATAN KELUARGA — Keguguran", grup: "RIWAYAT KESEHATAN KELUARGA", label: "Keguguran", idx: 141 },
        ],
    },
    "Rekap Lab & Non Lab": {
        kategori: "Rekap Lab & Non Lab",
        sheet: "Rekap Lab & Non Lab",
        barisGrup: 1,
        barisHeader: 2,
        kolom: [
            { key: "Hematologi Lengkap — Hemoglobin", grup: "Hematologi Lengkap", label: "Hemoglobin", idx: 11 },
            { key: "Hematologi Lengkap — Hematokrit", grup: "Hematologi Lengkap", label: "Hematokrit", idx: 12 },
            { key: "Hematologi Lengkap — Eritrosit", grup: "Hematologi Lengkap", label: "Eritrosit", idx: 13 },
            { key: "Hematologi Lengkap — MCV", grup: "Hematologi Lengkap", label: "MCV", idx: 14 },
            { key: "Hematologi Lengkap — MCH", grup: "Hematologi Lengkap", label: "MCH", idx: 15 },
            { key: "Hematologi Lengkap — MCHC", grup: "Hematologi Lengkap", label: "MCHC", idx: 16 },
            { key: "Hematologi Lengkap — RDW-CV", grup: "Hematologi Lengkap", label: "RDW-CV", idx: 17 },
            { key: "Hematologi Lengkap — Trombosit", grup: "Hematologi Lengkap", label: "Trombosit", idx: 18 },
            { key: "Hematologi Lengkap — Leukosit", grup: "Hematologi Lengkap", label: "Leukosit", idx: 19 },
            { key: "Hematologi Lengkap — Basofil", grup: "Hematologi Lengkap", label: "Basofil", idx: 20 },
            { key: "Hematologi Lengkap — Eosinofil", grup: "Hematologi Lengkap", label: "Eosinofil", idx: 21 },
            { key: "Hematologi Lengkap — Neutrofil", grup: "Hematologi Lengkap", label: "Neutrofil", idx: 22 },
            { key: "Hematologi Lengkap — Limfosit", grup: "Hematologi Lengkap", label: "Limfosit", idx: 23 },
            { key: "Hematologi Lengkap — Monosit", grup: "Hematologi Lengkap", label: "Monosit", idx: 24 },
            { key: "Hematologi Lengkap — LED", grup: "Hematologi Lengkap", label: "LED", idx: 25 },
            { key: "Hematologi Lengkap — GOT", grup: "Hematologi Lengkap", label: "GOT", idx: 26 },
            { key: "Hematologi Lengkap — GPT", grup: "Hematologi Lengkap", label: "GPT", idx: 27 },
            { key: "Hematologi Lengkap — Gamma GT", grup: "Hematologi Lengkap", label: "Gamma GT", idx: 28 },
            { key: "Hematologi Lengkap — HbA1c (NGSP)", grup: "Hematologi Lengkap", label: "HbA1c (NGSP)", idx: 29 },
            { key: "Hematologi Lengkap — HbA1c (IFCC)", grup: "Hematologi Lengkap", label: "HbA1c (IFCC)", idx: 30 },
            { key: "Hematologi Lengkap — Estimasi Glukosa Rata-rata (eAG)", grup: "Hematologi Lengkap", label: "Estimasi Glukosa Rata-rata (eAG)", idx: 31 },
            { key: "Hematologi Lengkap — Cholesterol Total", grup: "Hematologi Lengkap", label: "Cholesterol Total", idx: 32 },
            { key: "Hematologi Lengkap — Cholesterol LDL Direk", grup: "Hematologi Lengkap", label: "Cholesterol LDL Direk", idx: 33 },
            { key: "Hematologi Lengkap — Cholesterol HDL", grup: "Hematologi Lengkap", label: "Cholesterol HDL", idx: 34 },
            { key: "Hematologi Lengkap — Trigliserida", grup: "Hematologi Lengkap", label: "Trigliserida", idx: 35 },
            { key: "Hematologi Lengkap — Urea N", grup: "Hematologi Lengkap", label: "Urea N", idx: 36 },
            { key: "Hematologi Lengkap — Ureum", grup: "Hematologi Lengkap", label: "Ureum", idx: 37 },
            { key: "Hematologi Lengkap — Kreatinin", grup: "Hematologi Lengkap", label: "Kreatinin", idx: 38 },
            { key: "Hematologi Lengkap — eLFG (CKD-EPI)", grup: "Hematologi Lengkap", label: "eLFG (CKD-EPI)", idx: 39 },
            { key: "Hematologi Lengkap — Asam Urat", grup: "Hematologi Lengkap", label: "Asam Urat", idx: 40 },
            { key: "Hematologi Lengkap — HBsAg", grup: "Hematologi Lengkap", label: "HBsAg", idx: 41 },
            { key: "Hematologi Lengkap — Anti-HBs", grup: "Hematologi Lengkap", label: "Anti-HBs", idx: 42 },
            { key: "Urine Rutin — Warna", grup: "Urine Rutin", label: "Warna", idx: 43 },
            { key: "Urine Rutin — Kejernihan", grup: "Urine Rutin", label: "Kejernihan", idx: 44 },
            { key: "Urine Rutin — Berat Jenis", grup: "Urine Rutin", label: "Berat Jenis", idx: 45 },
            { key: "Urine Rutin — pH", grup: "Urine Rutin", label: "pH", idx: 46 },
            { key: "Urine Rutin — Lekosit Esterase", grup: "Urine Rutin", label: "Lekosit Esterase", idx: 47 },
            { key: "Urine Rutin — Nitrit", grup: "Urine Rutin", label: "Nitrit", idx: 48 },
            { key: "Urine Rutin — Albumin", grup: "Urine Rutin", label: "Albumin", idx: 49 },
            { key: "Urine Rutin — Glukosa", grup: "Urine Rutin", label: "Glukosa", idx: 50 },
            { key: "Urine Rutin — Keton", grup: "Urine Rutin", label: "Keton", idx: 51 },
            { key: "Urine Rutin — Urobilinogen", grup: "Urine Rutin", label: "Urobilinogen", idx: 52 },
            { key: "Urine Rutin — Bilirubin", grup: "Urine Rutin", label: "Bilirubin", idx: 53 },
            { key: "Urine Rutin — Darah (Blood)", grup: "Urine Rutin", label: "Darah (Blood)", idx: 54 },
            { key: "Urine Rutin — Eritrosit", grup: "Urine Rutin", label: "Eritrosit", idx: 55 },
            { key: "Urine Rutin — Lekosit", grup: "Urine Rutin", label: "Lekosit", idx: 56 },
            { key: "Urine Rutin — Silinder Hyalin", grup: "Urine Rutin", label: "Silinder Hyalin", idx: 57 },
            { key: "Urine Rutin — Silinder Lain-lain", grup: "Urine Rutin", label: "Silinder Lain-lain", idx: 58 },
            { key: "Urine Rutin — Epithel Gepeng", grup: "Urine Rutin", label: "Epithel Gepeng", idx: 59 },
            { key: "Urine Rutin — Epithel Transitional", grup: "Urine Rutin", label: "Epithel Transitional", idx: 60 },
            { key: "Urine Rutin — Epithel Tubulus Ginjal", grup: "Urine Rutin", label: "Epithel Tubulus Ginjal", idx: 61 },
            { key: "Urine Rutin — Bakteri", grup: "Urine Rutin", label: "Bakteri", idx: 62 },
            { key: "Urine Rutin — Kristal Normal", grup: "Urine Rutin", label: "Kristal Normal", idx: 63 },
            { key: "Urine Rutin — Kristal Abnormal", grup: "Urine Rutin", label: "Kristal Abnormal", idx: 64 },
            { key: "Urine Rutin — Lain-lain", grup: "Urine Rutin", label: "Lain-lain", idx: 65 },
            { key: "RONTGEN", grup: "Lainnya", label: "RONTGEN", idx: 66 },
            { key: "EKG", grup: "Lainnya", label: "EKG", idx: 67 },
            { key: "TREADMILL", grup: "Lainnya", label: "TREADMILL", idx: 68 },
            { key: "Audiometri", grup: "Lainnya", label: "Audiometri", idx: 69 },
            { key: "Spirometri", grup: "Lainnya", label: "Spirometri", idx: 70 },
        ],
    },
};

/** Kolom dikelompokkan menurut grup, urutan asli dipertahankan — untuk header colSpan. */
export function grupRekap(k: RekapKategori): { grup: string; kolom: KolomRekap[] }[] {
    const out: { grup: string; kolom: KolomRekap[] }[] = [];
    for (const kol of REKAP_DEFS[k].kolom) {
        const akhir = out[out.length - 1];
        if (akhir && akhir.grup === kol.grup) akhir.kolom.push(kol);
        else out.push({ grup: kol.grup, kolom: [kol] });
    }
    return out;
}

export function isRekap(kategori: string): kategori is RekapKategori {
    return (REKAP_KATEGORI as string[]).includes(kategori);
}
